"use client";

import { useState } from "react";
import { BookOpen, CheckCircle2, GraduationCap, Users } from "lucide-react";
import Link from "next/link";
import type { ClassroomData } from "@/lib/courses/classroom";
import { courseClassroomLearnerPath } from "@/lib/courses/context-navigation";

function learnerState(status: "not-started" | "in-progress" | "completed") { return status === "completed" ? "Terminé" : status === "in-progress" ? "En cours" : "Pas commencé"; }
function currentLessonLabel(status: "not-started" | "in-progress" | "completed") { return status === "completed" ? "Dernière leçon" : "Leçon en cours"; }

export function CourseClassroom({ data, archived, courseSlug }: { data: ClassroomData; archived: boolean; courseSlug: string }) {
  const [tab, setTab] = useState<"overview" | "learners">("overview");
  return <section className="course-classroom" aria-labelledby="classroom-title"><header className="course-classroom__heading"><div><p className="eyebrow"><GraduationCap size={15} aria-hidden="true" /> Classroom</p><h2 id="classroom-title">Suivi des apprenants</h2><p>{archived ? "Parcours archivé : ces données sont conservées en lecture seule." : "Vue opérationnelle des inscriptions et de la progression du parcours."}</p></div></header><nav className="course-classroom__tabs" aria-label="Sections Classroom"><button type="button" aria-current={tab === "overview" ? "page" : undefined} onClick={() => setTab("overview")}>Synthèse</button><button type="button" aria-current={tab === "learners" ? "page" : undefined} onClick={() => setTab("learners")}>Apprenants</button></nav>{data.totalLearners ? <><dl hidden={tab !== "overview"} className="course-classroom__summary" aria-label="Résumé Classroom"><div><Users size={17} aria-hidden="true" /><dt>Apprenants</dt><dd>{data.totalLearners}</dd></div><div><BookOpen size={17} aria-hidden="true" /><dt>Progression moyenne</dt><dd>{data.averageProgress} %</dd></div><div><CheckCircle2 size={17} aria-hidden="true" /><dt>Terminés</dt><dd>{data.completedLearners}</dd></div></dl><section hidden={tab !== "learners"} className="course-classroom__roster" aria-labelledby="classroom-roster-title"><div className="course-classroom__roster-heading"><div><p className="eyebrow">Apprenants</p><h3 id="classroom-roster-title">Progression du groupe</h3></div><p>{data.totalLearners} inscrit{data.totalLearners > 1 ? "s" : ""}</p></div><ul>{data.learners.map((learner) => <li key={learner.id}><span className="course-classroom__initials" aria-hidden="true">{learner.initials}</span><div className="course-classroom__identity"><strong>{learner.displayName}</strong><small>{learnerState(learner.status)}</small></div><div className="course-classroom__progress"><strong>{learner.progress} %</strong><span>{learner.completedLessons} / {learner.totalLessons} leçon{learner.totalLessons > 1 ? "s" : ""}</span><progress value={learner.progress} max={100} aria-label={`Progression de ${learner.displayName}: ${learner.progress} %`} /></div><div className="course-classroom__lesson"><span>{currentLessonLabel(learner.status)}</span><strong>{learner.currentLessonTitle ?? "Aucune leçon commencée"}</strong></div><Link className="course-classroom__learner-link" href={courseClassroomLearnerPath(courseSlug, learner.id)}>Voir le suivi</Link></li>)}</ul></section></> : <div className="course-classroom__empty"><Users size={20} aria-hidden="true" /><p>Aucun apprenant inscrit pour le moment.</p></div>}</section>;
}
