"use client";

import { useTransition } from "react";
import { Check, Handshake, X } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { resolveCourseCollaborationRequestAction, setCourseCollaborationRequestsEnabledAction } from "@/app/app/courses/collaboration-request-actions";
import type { CourseCollaborationRequest } from "@/lib/courses/collaboration-requests";

export function CourseCollaborationRequestsPanel({ courseId, enabled, available, requests, onFeedback }: { courseId: string; enabled: boolean; available: boolean; requests: CourseCollaborationRequest[]; onFeedback: (text: string, error?: boolean) => void }) {
  const [pending, startTransition] = useTransition();
  const run = (work: () => Promise<void>, success: string) => startTransition(async () => { try { await work(); onFeedback(success); } catch (reason) { onFeedback(reason instanceof Error ? reason.message : "La demande n'a pas pu être mise à jour.", true); } });
  if (!available) return <section className="collaboration-requests-owner"><h3>Demandes de collaboration</h3><p className="caption">Disponible après l&apos;application de la migration I.2.F.</p></section>;
  return <section id="collaboration-requests" className="collaboration-requests-owner" aria-labelledby="collaboration-requests-title"><div className="collaboration-requests-owner__heading"><div><p className="eyebrow"><Handshake size={15} /> Collaboration</p><h3 id="collaboration-requests-title">Demandes de collaboration</h3></div><label className="collaboration-requests-owner__toggle"><input type="checkbox" checked={enabled} disabled={pending} onChange={(event) => run(() => setCourseCollaborationRequestsEnabledAction(courseId, event.target.checked), event.target.checked ? "Demandes de collaboration activées." : "Demandes de collaboration désactivées.")} />Accepter les demandes de collaboration</label></div><p className="caption">Les apprenants inscrits pourront demander à rejoindre l&apos;équipe du parcours.</p>{requests.length > 0 && <ul>{requests.map((request) => <li key={request.requestId}><span className="collaborator-manager__initials" aria-hidden="true">{request.initials}</span><div><strong>{request.displayName}</strong><small>Demande reçue le {new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(new Date(request.createdAt))}</small>{request.message && <p>{request.message}</p>}</div><div className="collaboration-requests-owner__actions"><Button type="button" variant="secondary" disabled={pending} onClick={() => run(() => resolveCourseCollaborationRequestAction(courseId, request.requestId, "accepted", "viewer"), `${request.displayName} rejoint le parcours comme lecteur.`)}><Check size={16} /> Lecteur</Button><Button type="button" disabled={pending} onClick={() => run(() => resolveCourseCollaborationRequestAction(courseId, request.requestId, "accepted", "editor"), `${request.displayName} rejoint le parcours comme éditeur.`)}><Check size={16} /> Éditeur</Button><Button type="button" variant="ghost" disabled={pending} onClick={() => run(() => resolveCourseCollaborationRequestAction(courseId, request.requestId, "declined"), "Demande refusée.")}><X size={16} /> Refuser</Button></div></li>)}</ul>}</section>;
}