import { ArrowLeft, BookOpen, CheckCircle2, Circle, PlayCircle, UserRound } from "lucide-react";
import Link from "next/link";
import type { ClassroomLearnerDetail } from "@/lib/courses/classroom";
import { courseClassroomPath } from "@/lib/courses/context-navigation";

function enrollmentLabel(status: ClassroomLearnerDetail["status"]) { return status === "completed" ? "Terminé" : status === "in-progress" ? "En cours" : "Pas commencé"; }

export function LearnerProgressDetail({ courseSlug, detail, archived }: { courseSlug: string; detail: ClassroomLearnerDetail; archived: boolean }) {
  const currentLessonLabel = detail.status === "completed" ? "Dernière leçon" : "Leçon en cours";
  return <section className="learner-progress-detail" aria-labelledby="learner-progress-title"><Link className="learner-progress-detail__back" href={courseClassroomPath(courseSlug)}><ArrowLeft size={16} /> Retour au Classroom</Link><header className="learner-progress-detail__heading"><span className="course-classroom__initials" aria-hidden="true">{detail.initials}</span><div><p className="eyebrow"><UserRound size={15} aria-hidden="true" /> Apprenant</p><h2 id="learner-progress-title">{detail.displayName}</h2><p>{archived ? "Parcours archivé : suivi historique en lecture seule." : "Progression dans ce parcours uniquement."}</p></div></header><dl className="learner-progress-detail__summary"><div><BookOpen size={17} aria-hidden="true" /><dt>Progression</dt><dd>{detail.progress} %</dd><progress value={detail.progress} max={100} aria-label={`Progression de ${detail.displayName}: ${detail.progress} %`} /></div><div><CheckCircle2 size={17} aria-hidden="true" /><dt>Leçons terminées</dt><dd>{detail.completedLessons} / {detail.totalLessons}</dd></div><div><Circle size={17} aria-hidden="true" /><dt>Inscription</dt><dd>{enrollmentLabel(detail.status)}</dd></div></dl>{detail.currentLessonTitle && <section className="learner-progress-detail__current" aria-labelledby="learner-current-lesson"><p className="eyebrow"><PlayCircle size={15} aria-hidden="true" /> {currentLessonLabel}</p><h3 id="learner-current-lesson">{detail.currentLessonTitle}</h3></section>}<section className="learner-progress-detail__modules" aria-labelledby="learner-modules-title"><div><p className="eyebrow">Progression détaillée</p><h3 id="learner-modules-title">Modules</h3></div>{detail.modules.map((module) => <section className="learner-progress-detail__module" key={module.id}><header><div><h4>{module.title}</h4><p>{module.completedLessons} / {module.totalLessons} leçon{module.totalLessons > 1 ? "s" : ""}</p></div><strong>{module.progress} %</strong></header><progress value={module.progress} max={100} aria-label={`Progression du module ${module.title}: ${module.progress} %`} /><ul>{module.lessons.map((lesson) => <li key={lesson.id}><span>{lesson.state === "completed" ? "Terminé" : lesson.state === "current" ? "En cours" : "À faire"}</span><strong>{lesson.title}</strong>{lesson.durationMinutes != null && <small>{lesson.durationMinutes} min</small>}</li>)}</ul></section>)}</section></section>;
}