"use client";

import { useEffect, useState, useTransition } from "react";
import { Plus, Save } from "lucide-react";
import type { CourseDetail } from "@/lib/courses/contracts";
import { Button } from "@/components/ui/Button";
import { addLessonAction, addModuleAction, renameModuleAction, saveCourseMetadataAction } from "@/app/app/create/actions";
import { useForgeProposal } from "@/components/forge/ForgeProposalContext";

export function CourseEditor({ course }: { course: CourseDetail }) {
  const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const [draft, setDraft] = useState({ title: course.title, subtitle: course.subtitle ?? "", description: course.description ?? "" });
  const { proposal, setProposal } = useForgeProposal();
  useEffect(() => { if (!proposal || proposal.proposal.target.courseId !== course.id || proposal.proposal.target.lessonId || proposal.proposal.field !== "description" || !proposal.proposal.suggestedContent) return; const content = proposal.proposal.suggestedContent; queueMicrotask(() => { setDraft((current) => ({ ...current, description: content })); setMessage("Proposition appliquée localement. Sauvegardez pour la conserver."); setProposal(null); }); }, [course.id, proposal, setProposal]);
  const run = (action: () => Promise<void>, success: string) => startTransition(async () => { try { await action(); setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : "La sauvegarde a échoué."); } });
  return <div className="editor-stack"><form className="form authoring-form" onSubmit={(event) => { event.preventDefault(); run(() => saveCourseMetadataAction(course.id, new FormData(event.currentTarget)), "Informations sauvegardées."); }}><h2>Informations du parcours</h2><label>Titre<input name="title" value={draft.title} onChange={(event) => setDraft((current) => ({ ...current, title: event.target.value }))} required /></label><label>Résumé<input name="subtitle" value={draft.subtitle} onChange={(event) => setDraft((current) => ({ ...current, subtitle: event.target.value }))} /></label><label>Description<textarea name="description" value={draft.description} onChange={(event) => setDraft((current) => ({ ...current, description: event.target.value }))} required /></label><Button type="submit" disabled={pending}><Save size={17} /> {pending ? "Sauvegarde..." : "Sauvegarder"}</Button></form><section className="content-section"><div className="section-heading"><h2>Structure</h2><form action={(data) => run(() => addModuleAction(course.id, data), "Module ajouté.")}><input name="title" aria-label="Titre du nouveau module" placeholder="Nouveau module" required /><Button type="submit" variant="secondary"><Plus size={16} /> Module</Button></form></div>{course.outline.map((module) => <section id={`module-${module.id}`} className="program-module" key={module.id}><form className="inline-form" action={(data) => run(() => renameModuleAction(course.id, module.id, data), "Module renommé.")}><label>Titre du module<input name="title" defaultValue={module.moduleTitle} required /></label><Button type="submit" variant="ghost">Renommer</Button></form>{module.lessons.map((lesson) => <p key={lesson.id}>{lesson.title}</p>)}<form className="inline-form" action={(data) => run(() => addLessonAction(course.id, module.id, data), "Leçon ajoutée.")}><input name="title" aria-label={`Titre d'une leçon dans ${module.moduleTitle}`} placeholder="Nouvelle leçon" required /><Button type="submit" variant="ghost"><Plus size={16} /> Leçon</Button></form></section>)}</section>{message && <p className={message.includes("échoué") || message.includes("pouvez") ? "form-error" : "completion-state"} role="status">{message}</p>}</div>;
}
