import { ArrowRight, BarChart3, Clock3, Layers3, LoaderCircle, RefreshCw, Sparkles } from "lucide-react";
import { publicCourseFormatLabels, type PublicCoursePreview } from "@/lib/forge/public-contracts";
import { DomainMetadata } from "@/components/course/DomainMetadata";
import { Button } from "@/components/ui/Button";

export function GeneratedPath({ preview, domain, onDomainChange, domains, onRegenerate, onAccept, acceptLabel = "Créer ce parcours", acceptKind = "create", busy = false, busyLabel, canAccept = true }: {
  preview: PublicCoursePreview; domain: string; onDomainChange(value: string): void; domains: Array<{ id?: string; name: string }>;
  onRegenerate(): void; onAccept(): void; acceptLabel?: string; acceptKind?: "create" | "continue"; busy?: boolean; busyLabel?: string; canAccept?: boolean;
}) {
  const workspace = acceptKind === "create";
  if (!workspace) return <section className="generated-path" aria-label="Proposition Forge"><header className="generated-path__heading"><div><p className="eyebrow"><Sparkles size={15} /> Proposition Forge</p><h2>{preview.title}</h2><p>{preview.summary}</p></div><Button type="button" variant="secondary" onClick={onRegenerate} disabled={busy}><RefreshCw size={15} />Régénérer</Button></header><div className="generated-path__guidance"><p className="caption">{preview.suggestedDomainLabel ? `Domaine suggéré par Forge : ${preview.suggestedDomainLabel}` : "Aucun domaine suggéré pour le moment."}</p><label>Associer à un domaine existant<select value={domains.some((item) => item.name === domain) ? domain : ""} onChange={(event) => onDomainChange(event.target.value)}><option value="">Aucun domaine pour le moment</option>{domains.map((item) => <option key={item.id ?? item.name} value={item.name}>{item.name}</option>)}</select></label><span><Layers3 size={16} />{publicCourseFormatLabels[preview.format]} · {preview.modules.length} modules</span>{preview.estimatedDuration && <span><Clock3 size={16} />{preview.estimatedDuration}</span>}{preview.level && <span><BarChart3 size={16} />{preview.level}</span>}</div><div className="generated-path__outcomes"><strong>Objectifs du parcours</strong><ul>{preview.learningOutcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ul></div><div className="generated-path__modules">{preview.modules.map((module, index) => <article key={`${module.title}-${index}`}><span>{index + 1}</span><div><h3>{module.title}</h3><p>{module.summary}</p><ul>{module.outcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ul>{module.estimatedDuration && <small>{module.estimatedDuration}</small>}</div></article>)}</div><div className="generated-path__accept"><p>La création se fera après connexion. Le domaine pourra être choisi plus tard.</p><Button type="button" onClick={onAccept} disabled={busy || !canAccept} aria-busy={busy}>{busy ? <><LoaderCircle className="create-spinner" size={16} />{busyLabel ?? "Forge prépare la proposition…"}</> : <><ArrowRight size={16} />{acceptLabel}</>}</Button></div></section>;
  const lessonCount = preview.modules.reduce((total, item) => total + item.outcomes.length, 0);
  return <section className={`generated-path${workspace ? " generated-path--workspace" : ""}`} aria-label="Proposition Forge" id={workspace ? "generated-proposal" : undefined}>
    <header className="generated-path__heading"><div><p className="eyebrow"><Sparkles size={15} aria-hidden="true" /> Proposition Forge · non enregistrée</p><h2>{preview.title}</h2><p>{preview.summary}</p></div><div className="generated-path__heading-actions">{workspace && <a href="#create-intent">Modifier l’intention</a>}<Button type="button" variant="secondary" onClick={onRegenerate} disabled={busy}><RefreshCw size={15} aria-hidden="true" />Régénérer</Button></div></header>
    <div className="generated-path__guidance"><DomainMetadata domain={domains.some((item) => item.name === domain) ? domain : null} /><p className="caption">{preview.suggestedDomainLabel ? `Suggestion Forge : ${preview.suggestedDomainLabel}` : "Aucun domaine suggéré pour le moment."}</p><label>Associer à un domaine existant<select value={domains.some((item) => item.name === domain) ? domain : ""} onChange={(event) => onDomainChange(event.target.value)}><option value="">Aucun domaine pour le moment</option>{domains.map((item) => <option key={item.id ?? item.name} value={item.name}>{item.name}</option>)}</select></label>{!canAccept && workspace && <span role="status">Cette proposition ne peut pas encore être créée.</span>}</div>
    <div className="generated-path__summary"><span><Layers3 size={16} aria-hidden="true" />{preview.modules.length} modules · {lessonCount} leçons proposées</span><span>{publicCourseFormatLabels[preview.format]}</span>{preview.estimatedDuration && <span><Clock3 size={16} aria-hidden="true" />{preview.estimatedDuration}</span>}{preview.level && <span>{preview.level}</span>}</div>
    <div className="generated-path__outcomes"><strong>Objectifs du parcours</strong><ul>{preview.learningOutcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ul></div>
    <div className="generated-path__modules" aria-label="Structure proposée">{preview.modules.map((module, index) => <article key={`${module.title}-${index}`}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{module.title}</h3><p>{module.summary}</p><strong>Leçons proposées</strong><ol>{module.outcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ol>{module.estimatedDuration && <small>{module.estimatedDuration}</small>}</div></article>)}</div>
    <div className="generated-path__accept"><p>{workspace ? "Créer ce parcours enregistrera la proposition, ses modules et les leçons proposées. Vous pourrez ensuite modifier leur contenu." : "La création se fera après connexion. Le domaine pourra être choisi plus tard."}</p><Button type="button" onClick={onAccept} disabled={busy || !canAccept} aria-busy={busy}>{busy ? <><LoaderCircle className="create-spinner" size={16} aria-hidden="true" />{busyLabel ?? "Forge prépare la proposition…"}</> : <>{workspace ? <Sparkles size={16} aria-hidden="true" /> : <ArrowRight size={16} aria-hidden="true" />}{acceptLabel}</>}</Button></div>
  </section>;
}
