import { ArrowRight, BarChart3, Clock3, Layers3, LoaderCircle, RefreshCw, Sparkles } from "lucide-react";
import { publicCourseFormatLabels, type PublicCoursePreview } from "@/lib/forge/public-contracts";
import { DomainMetadata } from "@/components/course/DomainMetadata";
import { Button } from "@/components/ui/Button";
import type { CreationProposalState } from "@/lib/forge/creation-flow";
import { creationProposalLabels, selectedCreationDomain } from "@/lib/forge/creation-flow";

export function GeneratedPath({ preview, domain, domainId, onDomainChange, onAdjust, domains, onRegenerate, onAccept, acceptLabel = "Créer le parcours", acceptKind = "create", busy = false, busyLabel, canAccept = true, proposalState = "generated" }: {
  preview: PublicCoursePreview; domain: string; domainId?: string; onDomainChange(value: string): void; onAdjust?(patch: Pick<PublicCoursePreview, "title" | "summary">): void; domains: Array<{ id?: string; name: string }>;
  onRegenerate(): void; onAccept(): void; acceptLabel?: string; acceptKind?: "create" | "continue"; busy?: boolean; busyLabel?: string; canAccept?: boolean; proposalState?: CreationProposalState;
}) {
  const workspace = acceptKind === "create";
  const selectedDomain = domainId ? selectedCreationDomain(domains.filter((item): item is { id: string; name: string } => Boolean(item.id)), domainId) : null;
  if (!workspace) return <section className="generated-path" aria-label="Proposition Forge"><header className="generated-path__heading"><div><p className="eyebrow"><Sparkles size={15} /> Proposition Forge</p><h2>{preview.title}</h2><p>{preview.summary}</p></div><Button type="button" variant="secondary" onClick={onRegenerate} disabled={busy}><RefreshCw size={15} />Régénérer</Button></header><div className="generated-path__guidance"><p className="caption">{preview.suggestedDomainLabel ? `Domaine suggéré par Forge : ${preview.suggestedDomainLabel}` : "Aucun domaine suggéré pour le moment."}</p><label>Associer à un domaine existant<select value={domains.some((item) => item.name === domain) ? domain : ""} onChange={(event) => onDomainChange(event.target.value)}><option value="">Aucun domaine pour le moment</option>{domains.map((item) => <option key={item.id ?? item.name} value={item.name}>{item.name}</option>)}</select></label><span><Layers3 size={16} />{publicCourseFormatLabels[preview.format]} · {preview.modules.length} modules</span>{preview.estimatedDuration && <span><Clock3 size={16} />{preview.estimatedDuration}</span>}{preview.level && <span><BarChart3 size={16} />{preview.level}</span>}</div><div className="generated-path__outcomes"><strong>Objectifs du parcours</strong><ul>{preview.learningOutcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ul></div><div className="generated-path__modules">{preview.modules.map((module, index) => <article key={`${module.title}-${index}`}><span>{index + 1}</span><div><h3>{module.title}</h3><p>{module.summary}</p><ul>{module.outcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ul>{module.estimatedDuration && <small>{module.estimatedDuration}</small>}</div></article>)}</div><div className="generated-path__accept"><p>La création se fera après connexion. Le domaine pourra être choisi plus tard.</p><Button type="button" onClick={onAccept} disabled={busy || !canAccept} aria-busy={busy}>{busy ? <><LoaderCircle className="create-spinner" size={16} />{busyLabel ?? "Forge prépare la proposition…"}</> : <><ArrowRight size={16} />{acceptLabel}</>}</Button></div></section>;
  const lessonCount = preview.modules.reduce((total, item) => total + item.outcomes.length, 0);
  return <section className={`generated-path${workspace ? " generated-path--workspace" : ""}`} aria-label="Proposition Forge" id={workspace ? "generated-proposal" : undefined}>
    <header className="generated-path__heading"><div><p className="eyebrow"><Sparkles size={15} aria-hidden="true" /> {creationProposalLabels[proposalState]}</p>{workspace && onAdjust ? <label className="generated-path__edit-field">Titre proposé<input value={preview.title} onChange={(event) => onAdjust({ title: event.target.value, summary: preview.summary })} maxLength={180} /></label> : <h2>{preview.title}</h2>}{workspace && onAdjust ? <label className="generated-path__edit-field">Résumé proposé<textarea value={preview.summary} onChange={(event) => onAdjust({ title: preview.title, summary: event.target.value })} maxLength={1000} /></label> : <p>{preview.summary}</p>}</div><div className="generated-path__heading-actions">{workspace && <a href="#create-intent">Modifier l’intention</a>}<Button type="button" variant="secondary" onClick={onRegenerate} disabled={busy}><RefreshCw size={15} aria-hidden="true" />Regénérer la proposition</Button></div></header>
    <div className="generated-path__guidance"><DomainMetadata domain={workspace ? selectedDomain?.name ?? null : domains.some((item) => item.name === domain) ? domain : null} />{workspace ? <label>Choisir le domaine<select value={domainId ?? ""} onChange={(event) => onDomainChange(event.target.value)}><option value="">Sélectionnez un domaine</option>{domains.map((item) => <option key={item.id ?? item.name} value={item.id ?? ""}>{item.name}</option>)}</select></label> : <><p className="caption">{preview.suggestedDomainLabel ? `Domaine suggéré par Forge : ${preview.suggestedDomainLabel}` : "Aucun domaine suggéré pour le moment."}</p><label>Associer à un domaine existant<select value={domains.some((item) => item.name === domain) ? domain : ""} onChange={(event) => onDomainChange(event.target.value)}><option value="">Aucun domaine pour le moment</option>{domains.map((item) => <option key={item.id ?? item.name} value={item.name}>{item.name}</option>)}</select></label></>}{!canAccept && workspace && <span role="status">Choisissez un domaine avant de créer le parcours.</span>}</div>
    <div className="generated-path__summary"><span><Layers3 size={16} aria-hidden="true" />{preview.modules.length} modules · {lessonCount} leçons proposées</span><span>{publicCourseFormatLabels[preview.format]}</span>{preview.estimatedDuration && <span><Clock3 size={16} aria-hidden="true" />{preview.estimatedDuration}</span>}{preview.level && <span>{preview.level}</span>}</div>
    <div className="generated-path__outcomes"><strong>Objectifs du parcours</strong><ul>{preview.learningOutcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ul></div>
    <div className="generated-path__modules" aria-label="Structure proposée">{preview.modules.map((module, index) => <article key={`${module.title}-${index}`}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{module.title}</h3><p>{module.summary}</p><strong>Leçons proposées</strong><ol>{module.outcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ol>{module.estimatedDuration && <small>{module.estimatedDuration}</small>}</div></article>)}</div>
    <div className="generated-path__accept"><p>{workspace ? "Créer le parcours enregistrera cette proposition, ses modules et les leçons proposées comme brouillon privé. Vous pourrez ensuite poursuivre dans l’éditeur." : "La création se fera après connexion. Le domaine pourra être choisi plus tard."}</p><Button type="button" onClick={onAccept} disabled={busy || !canAccept} aria-busy={busy}>{busy ? <><LoaderCircle className="create-spinner" size={16} aria-hidden="true" />{busyLabel ?? "Forge prépare la proposition…"}</> : <>{workspace ? <Sparkles size={16} aria-hidden="true" /> : <ArrowRight size={16} aria-hidden="true" />}{acceptLabel}</>}</Button></div>
  </section>;
}
