"use client";
import { ArrowRight, Compass, LoaderCircle, PenLine, Sparkles } from "lucide-react";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { generatePublicPreviewAction } from "@/app/actions/public-preview";
import { FormatSelector } from "./FormatSelector";
import { GeneratedPath } from "./GeneratedPath";
import { PUBLIC_DRAFT_KEY, serializePublicDraft, type PublicCourseFormat, type PublicCoursePreview } from "@/lib/forge/public-contracts";
import { Button } from "@/components/ui/Button";

const errorMessages = { invalid_request: "Décrivez votre intention en au moins 12 caractères.", not_configured: "Forge IA n'est pas configuré pour le moment.", rate_limited: "Vous avez atteint la limite de previews. Réessayez dans un moment.", timeout: "Forge a mis trop de temps à répondre. Réessayez.", provider_auth: "Forge est temporairement indisponible.", provider_not_found: "Forge est temporairement indisponible.", provider_network: "Forge est temporairement indisponible.", provider_error: "Forge n'a pas pu préparer la proposition.", invalid_result: "La proposition reçue est incomplète. Réessayez." };
export function PublicIntentExperience({ domains, authenticated }: { domains: Array<{ name: string }>; authenticated: boolean }) {
  const router = useRouter(); const [intent, setIntent] = useState(""); const [format, setFormat] = useState<PublicCourseFormat>(); const [preview, setPreview] = useState<PublicCoursePreview>(); const [domain, setDomain] = useState(""); const [error, setError] = useState(""); const [feedback, setFeedback] = useState(""); const [pending, startTransition] = useTransition();
  function generate() { setError(""); setFeedback(""); startTransition(async () => { const result = await generatePublicPreviewAction({ intent, format, domain: domain || undefined }); if (!result.ok) return setError(errorMessages[result.error]); const updating = Boolean(preview); const changed = JSON.stringify(preview) !== JSON.stringify(result.preview); setPreview(result.preview); setFormat(result.preview.format); setDomain(result.preview.suggestedDomainLabel ?? ""); if (updating) setFeedback(changed ? "Proposition mise à jour." : "La proposition est déjà à jour."); }); }
  function continueFlow() { if (!preview) return; localStorage.setItem(PUBLIC_DRAFT_KEY, serializePublicDraft({ intent, format, domain, preview, lifecycle: "AUTH_PENDING" })); router.push(authenticated ? "/app/create?from=public" : "/login?next=/app/create?from=public"); }
  const Root = authenticated ? "section" : "main";
  return <Root className={`public-home${authenticated ? " public-home--embedded" : ""}`}><section className="public-home__hero"><div className="public-home__copy"><p className="eyebrow"><Sparkles size={15} aria-hidden="true" /> {authenticated ? "Votre espace Forge" : "Apprendre · Créer · Partager"}</p>{authenticated ? <h1>Que souhaitez-vous apprendre, créer ou transmettre&nbsp;?</h1> : <h1>Quel savoir allez-vous <em>construire</em> aujourd&apos;hui&nbsp;?</h1>}<p className="lede">Transformez une idée, un besoin ou une question en parcours d&apos;apprentissage, avec l&apos;IA.</p><div className="intent-composer"><label htmlFor="public-intent" className="sr-only">Décrivez votre intention d’apprentissage ou de création</label><div><Sparkles aria-hidden="true" /><textarea id="public-intent" value={intent} onChange={(event) => setIntent(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); generate(); } }} maxLength={500} placeholder="Décrivez ce que vous souhaitez apprendre, créer ou transmettre…" /><button type="button" onClick={generate} disabled={pending || intent.trim().length < 12} aria-label={pending ? preview ? "Forge met à jour la proposition…" : "Forge prépare une proposition…" : preview ? "Mettre à jour la proposition" : "Générer le parcours"}>{pending ? <LoaderCircle className="create-spinner" /> : authenticated ? <><Sparkles size={16} aria-hidden="true" /><span>Créer avec Forge</span></> : <ArrowRight />}</button></div><FormatSelector value={format} onChange={setFormat} /></div>{pending && <p className="generation-status" role="status">{preview ? "Forge met à jour la proposition…" : "Forge prépare une proposition…"}</p>}{feedback && <p className="completion-state" role="status">{feedback}</p>}{error && <p className="form-error" role="alert">{error}</p>}<div className="public-home__links">{authenticated && <Button href="/app/create" variant="secondary"><PenLine size={16} aria-hidden="true" />Ouvrir l’atelier de création</Button>}<Button href="/app/explore" variant="secondary"><Compass size={16} aria-hidden="true" />Explorer les parcours</Button></div></div>{!authenticated && <div className="public-home__art" aria-hidden="true"><span><Sparkles /></span><span>Idée</span><span>Structure</span><span>Apprentissage</span></div>}</section>{preview && <GeneratedPath preview={preview} domain={domain} onDomainChange={setDomain} domains={domains} onRegenerate={generate} onAccept={continueFlow} acceptLabel="Continuer avec Forge" acceptKind="continue" busy={pending} />}</Root>;
}
